server:
  port: 8080
logging.level.org.springframework.web: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    tomcat:
      max-active: 10
      max-idle: 8
      max-wait: 1000
      min-evictable-idle-time-millis: 1000
      min-idle: 8
      time-between-eviction-runs-millis: 1
    jdbc-url: 'jdbc:h2:file:~/shopping'
    url: 'jdbc:h2:file:~/shopping'
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    url: 'jdbc:h2:file:~/shopping'

#Same definition as what was put in the PersistenceConfiguration.flywayDataSource
#Defined as datasource.flyway so that's the organization we use here.
datasource:
  flyway:
    jdbc-url: 'jdbc:h2:file:~/shopping'
    url: 'jdbc:h2:file:~/shopping'
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    validate-on-migrate: false
